<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-16 11:18
=======
# Generated by Django 4.2.5 on 2023-10-07 11:48
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("percent_promo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("label", models.CharField(max_length=64)),
=======
                ("label", models.CharField(max_length=64, unique=True)),
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
            ],
        ),
        migrations.CreateModel(
            name="VerifAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=64, unique=True)),
                ("verification", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_label", models.CharField(max_length=24)),
                ("description", models.CharField(max_length=256)),
                ("image", models.CharField(max_length=64, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
<<<<<<< HEAD
                ("reduction", models.DecimalField(decimal_places=2, max_digits=10)),
                ("begin_promo", models.DateField(null=True)),
                ("end_promo", models.DateField(null=True)),
=======
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="promo.category"
                    ),
                ),
<<<<<<< HEAD
=======
                (
                    "promo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promo.promotion",
                    ),
                ),
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
<<<<<<< HEAD
=======
                ("verification", models.CharField(max_length=128)),
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
                ("is_staff", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
<<<<<<< HEAD
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promo.role",
                    ),
                ),
                (
=======
>>>>>>> deb99e6569ee3246687f75e57b26335889c71f4b
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
