# Generated by Django 4.2.5 on 2023-10-03 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promo.promotion",
            ),
        ),
    ]
