# Generated by Django 4.2.5 on 2023-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="label",
            field=models.CharField(max_length=64),
        ),
    ]
