# Generated by Django 4.2.5 on 2023-10-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0002_alter_role_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promo.role",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="promo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promo.promotion",
            ),
        ),
    ]
