# Generated by Django 4.2.5 on 2023-10-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0002_product_promo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="product_promo",
        ),
        migrations.AlterField(
            model_name="product",
            name="promo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promo.promotion",
            ),
        ),
    ]
