# Generated by Django 4.2.5 on 2023-10-07 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0003_user_role_alter_product_promo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification",
        ),
    ]
