# Generated by Django 4.2.6 on 2023-10-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0004_remove_user_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="product_promo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promo.product",
            ),
        ),
    ]
