# Generated by Django 4.2.6 on 2023-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0005_promotion_product_promo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="promo",
        ),
        migrations.AddField(
            model_name="product",
            name="begin_promo",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="end_promo",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="reduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
